gulpjs/vinyl

- README.md
Greetings,
not sure if this is intended, but possible arguments for `file.clone()` are not documented on the Readme.
> Document `file.clone()` arguments

- README.md
Fix #47.
* Document `path`
* Document `history`
* Document `options.history`
* The `options.path` documentation said the default value is `null`, but in reality it's `undefined`. I updated the documentation to reflect that. Or does the default value actually need to be `null`?
> Update docs for `path` and `history`

- README.md
- index.js
- package.json
- test/File.js
Not sure if you guys would consider this bloat or a useful feature, but I often find myself wanting these pathname-style helpers when working with vinyl Files. Cheers!
> Add dirname, basename and extname getters

- README.md
#46 inadvertently removed some newlines from the README. This adds them back in as `<br>` tags instead of trailing whitespace.
> Add explicit newlines to readme

- index.js
- test/File.js
According to [docs](https://github.com/danielhusar/vinyl#cloneopt) custom attributes should be deep cloned by default, but they are not at the moment.
> Fix file clone options

- lib/isBuffer.js
`instanceof` [doesnt work for browserified code](https://github.com/feross/buffer#important-always-use-bufferisbuffer-instead-of-instanceof-buffer) 
So I changed this to just use Buffer.isBuffer.
probably could just remove the entire 'isBuffer' module, but I left it to be consistent with the other packages.
> use Buffer.isBuffer instead of instanceof

- index.js
- test/File.js
As discussed in [#1461](https://github.com/gulpjs/gulp/issues/1461), I think this covers the simple case.
Note: I had to adjust tests in `vinyl-fs` to get them to pass against `vinyl` with this patch, will submit a PR for that as well.
Edit: and [here](https://github.com/gulpjs/vinyl-fs/pull/143) it is.
> Set atime, mtime and ctime from contents accessors

- package.json
As discussed in #76 this PR adds an NPM script for changelog creation.
Please note that github-changes is a bit greedy towards Github API. As is, the script is limited with [Github's API limits](https://developer.github.com/v3/#rate-limiting). `github-changes` has a way to authenticate in order to get a higher rate limit, using a Github API token. However, this kind of token-based authentication can not be hard-coded, since tokens must remain secret.
To circumvent this, one could install `github-changes` globally, and run
```
github-changes -o gulpjs -r vinyl -b master -f ./CHANGELOG.md --order-semver --use-commit-body -a -k YOUR_GITHUB_TOKEN
```
> chore: add NPM script for changelog

- index.js
- test/File.js
Changes `#clone()` to return `new this.constructor()` instead of `new File()` so it works properly even on objects extended from Vinyl.
> Clone with constructor

- README.md
- index.js
- test/File.js
Currently, when doing this:
```js
var file = new Vinyl({
path: __dirname + '/index.js',
sourceMap: {}
});
```
`sourceMap` and any other custom properties are ignored. This PR will make constructor extend `this` with all custom props passed in the configuration object.
It'll make creating Vinyl files a bit faster and more comfy.
I'm also moving check for custom properties from that multiline `if` statement to a dedicated static method `File.isCustomProp(key)` which relies on `File.builtInFields` array to check if a key is a custom property.
This is than used in `#clone()`, as well as constructor, and could be used in `#toJSON()` method from other PR.
It also allows anyone that extends from `Vinyl` to extend their `ExtendedVinyl.builtInFields` with their own props that shouldn't be cloned.
> Make constructor set custom properties

- index.js
- test/File.js
@contra please review.  I am linking these changes into my local vinyl-fs to utilize the changes and things seem to be working.  I avoided a bunch of throws to allow for this to be released as a minor (I think it should be fine as that).
> New: Add isSymbolic method and symlink property (closes #79)

- package.json
- test/File.js
@phated I've added a test, and found a bug in `cloneable-readable` in the process.
The test fails on master, meaning that the clone is keeping the content of the stream in memory.
I've also make it error if cloning a stream that was already started.
See #102.
> Added test for clone stream behavior and bumped cloneable-readable

- package.json
To address for https://github.com/mcollina/cloneable-readable/pull/2
> Bumped cloneable-readable v0.4.0.

- index.js
- package.json
- test/File.js
__Don't Merge__
@mcollina was this what you were thinking for the usage of `cloneable-readable` in the #85 discussion?  I'm not sure if I implemented with the same vision, any guidance or corrections would be really helpful.
> Breaking: Use cloneable-readable to clone streams - possibly breaking (closes #85)

- index.js
- package.json
- test/file.js
Updated for https://github.com/mcollina/cloneable-readable/pull/3
> Updated to leverate the latest cloneable readable

- package.json
Nothing change, but this mark cloneable-readable as stable.
> Use v1.0.0 of cloneable-readable

- index.js
- test/file.js
Node.js 11 removed support for the `inspect` property on objects as
custom inspect functions. Instead, this can be done by using the
util.inspect.custom symbol that is used here instead. To keep it
backwarts compatible the old function stays in place.
The README actually has a reference to this as well. However, the old
inspect function will not be called by Node.js 11 anymore. I am not really
sure how to properly reflect that and just kept it as it is.
> Fix: update custom inspection to use a symbol

- README.md
- package.json
- test/file.js
Refs: https://github.com/nodejs/citgm/issues/605
Refs: https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor
> Do not use the deprecated Buffer() constructor

- index.js
- test/file.js
> fix file.clone() if file is a symbolic link

- README.md
The URL of GitHub workflow badge was changed by badges/shields's issue `#8671`.
This PR modifies the URL in `README.md`.
> chore: Normalize repository

- index.js
- package.json
… is deprecated.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors#creating_a_shallow_copy
Related to https://github.com/gulpjs/vinyl-fs/issues/356
Related to https://github.com/gulpjs/vinyl-fs/issues/354
> fix: Drop clone-stats dependency by cloning with `Object.create`
